<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=c23b1bbe-2530-4f95-bd0d-a33400cd3072.sqlserver.sequelizer.com;Persist Security Info=True;User ID=tlmfurihbcfzlncr" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Accessory" Member="Accessory">
    <Type Name="Accessory">
      <Column Name="student" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="assignment" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="Assignment_Accessory" Member="Assignment1" ThisKey="assignment" OtherKey="id" Type="Assignment" IsForeignKey="true" />
      <Association Name="Student_Accessory" Member="Student1" ThisKey="student" OtherKey="username" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Answer" Member="Answer">
    <Type Name="Answer">
      <Column Name="student" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="problem" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="score" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Association Name="Problem_Answer" Member="Problem1" ThisKey="problem" OtherKey="id" Type="Problem" IsForeignKey="true" />
      <Association Name="Student_Answer" Member="Student1" ThisKey="student" OtherKey="username" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Assignment" Member="Assignment">
    <Type Name="Assignment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="course" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="descrip" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="start_time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="end_time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="major" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Assignment_Accessory" Member="Accessory" ThisKey="id" OtherKey="assignment" Type="Accessory" />
      <Association Name="Assignment_Problem" Member="Problem" ThisKey="id" OtherKey="assignment" Type="Problem" />
      <Association Name="Course_Assignment" Member="Course1" ThisKey="course" OtherKey="num" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Course">
    <Type Name="Course">
      <Column Name="num" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="teacher" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="start_time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="end_time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="Course_Assignment" Member="Assignment" ThisKey="num" OtherKey="course" Type="Assignment" />
      <Association Name="Course_Student_Course" Member="Student_Course" ThisKey="num" OtherKey="course" Type="Student_Course" />
      <Association Name="Teacher_Course" Member="Teacher1" ThisKey="teacher" OtherKey="username" Type="Teacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Problem" Member="Problem">
    <Type Name="Problem">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="assignment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="descrip" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="score" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="Problem_Answer" Member="Answer" ThisKey="id" OtherKey="problem" Type="Answer" />
      <Association Name="Assignment_Problem" Member="Assignment1" ThisKey="assignment" OtherKey="id" Type="Assignment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Student">
    <Type Name="Student">
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="passwd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="major" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Student_Accessory" Member="Accessory" ThisKey="username" OtherKey="student" Type="Accessory" />
      <Association Name="Student_Answer" Member="Answer" ThisKey="username" OtherKey="student" Type="Answer" />
      <Association Name="Student_Student_Course" Member="Student_Course" ThisKey="username" OtherKey="student" Type="Student_Course" />
    </Type>
  </Table>
  <Table Name="dbo.Student_Course" Member="Student_Course">
    <Type Name="Student_Course">
      <Column Name="student" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="course" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Course_Student_Course" Member="Course1" ThisKey="course" OtherKey="num" Type="Course" IsForeignKey="true" />
      <Association Name="Student_Student_Course" Member="Student1" ThisKey="student" OtherKey="username" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teacher">
    <Type Name="Teacher">
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="passwd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Teacher_Course" Member="Course" ThisKey="username" OtherKey="teacher" Type="Course" />
    </Type>
  </Table>
</Database>